locale: "ja-JP"
title: kinkinkon1009's memo
description: "This is my blog."
url: "https://kinkinkon1009.github.io"
baseurl: "/memo"
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "G-LXPR5NCQCQ"
twitter:
  username: KanechikaAyumu
liquid:
  error_mode: strict
paginate: 20
paginate_path: /page:num/
search_full_content: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true  
author:
  name: Ayumu Kanechika
  twitter: KanechikaAyumu
  links:
    - title: Twitter
      url: https://x.com/KanechikaAyumu
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/kinkinkon1009
      icon: fab fa-github-square
footer_links:
  - title: Twitter
    url: https://x.com/KanechikaAyumu
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/kinkinkon1009
    icon: fab fa-github-square
  